INSERT INTO Persons (_id, Firstname, Lastname) VALUES
                                                   (1,'Volodymyr','Zelenskyy'),
                                                   (2,'Friedrich','Merz'),
                                                   (3,'Emmanuel','Macron'),
                                                   (4,'Cyril','Ramaphosa'),
                                                   (5,'Luiz Inácio','Lula da Silva'),
                                                   (6,'Narendra','Modi'),
                                                   (7,'Xi','Jinping'),
                                                   (8,'Fumio','Kishida'),
                                                   (9,'Ibrahim','Iskandar'),
                                                   (10,'Alberto','Fernández'),
                                                   (11,'Giorgia','Meloni'),
                                                   (12,'Andrés','Manuel López Obrador'),
                                                   (13,'Rishi','Sunak'),
                                                   (14,'Recep Tayyip','Erdoğan'),
                                                   (15,'Joko','Widodo'),
                                                   (16,'Abdelmadjid','Tebboune'),
                                                   (17,'Pedro Sánchez','García'),
                                                   (18,'Justin','Trudeau'),
                                                   (19,'Fabiola','Yáñez'),
                                                   (20,'Volker','Bouffier');


INSERT INTO Countries (_id, Name, Persons__id) VALUES
                                                   (1, 'Österreich', 1),
                                                   (2, 'Deutschland', 2),
                                                   (3, 'Frankreich', 3),
                                                   (4, 'Italien', 4),
                                                   (5, 'Spanien', 5),
                                                   (6, 'Portugal', 6),
                                                   (7, 'Schweiz', 7),
                                                   (8, 'Belgien', 8),
                                                   (9, 'Niederlande', 9),
                                                   (10, 'Luxemburg', 10),
                                                   (11, 'Norwegen', 11),
                                                   (12, 'Schweden', 12),
                                                   (13, 'Finnland', 13),
                                                   (14, 'Dänemark', 14),
                                                   (15, 'Polen', 15),
                                                   (16, 'Tschechien', 16),
                                                   (17, 'Ungarn', 17),
                                                   (18, 'Slowenien', 18),
                                                   (19, 'Kroatien', 19),
                                                   (20, 'Serbien', 20);

